require 'nokogiri'
require 'open-uri'
require 'yaml'

# Fetch the HTML content from the URL
url = 'https://developer.service.hmrc.gov.uk/api-documentation/docs/api?filter=income-tax-mtd'
doc = Nokogiri::HTML(URI.open(url))

# Find all the hyperlinks where the anchor text ends with "(MTD)"
links = doc.css('a[href]').select { |link| link.text.strip.end_with?('(MTD)') }

# Open the output file
File.open('api-list.md', 'w') do |file|
  file.puts "Warning: this list was generated by running get_endpoint_list.rb and is not updated automatically."
  file.puts "The list is generated based on the content of the public API documentation."
  file.puts "To generate an up-to-date list, run get_endpoint_list.rb."
  file.puts ""

  # Process each link
  links.each do |link|
    clean_name = link.text.strip.gsub(/\s*\(MTD\)\z/, '')
    api_url = URI.join('https://developer.service.hmrc.gov.uk', link['href']).to_s
    resolved_url = api_url + '/oas/resolved'

    begin
      # Fetch the YAML content from the resolved URL
      yaml_content = URI.open(resolved_url).read
      yaml_data = YAML.safe_load(yaml_content, permitted_classes: [Date, Time])

      version = yaml_data.dig('info', 'version') || '?'
      api_details = "API: [#{clean_name}](#{api_url})\n(Version #{version})"

      puts api_details
      file.puts api_details
      file.puts ""

      if yaml_data['paths']
        yaml_data['paths'].each do |path, methods|
          methods.each do |method, details|
            summary = details['summary']
            puts "- Endpoint: #{summary}"
            file.puts "- Endpoint: #{summary}"
          end
        end
      else
        puts "*** Monolith detected, not listing endpoints to avoid problems with duplicate endpoint names"
        file.puts "  - Skipping monolith endpoints to avoid problems with duplicate endpoint names"
      end
      file.puts ""
    rescue OpenURI::HTTPError => e
      puts "Error fetching YAML content for #{resolved_url}: #{e.message}"
    rescue Psych::SyntaxError => e
      puts "Error parsing YAML content for #{resolved_url}: #{e.message}"
    end
  end
end